[package]
name = "divviup-client"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
version.workspace = true
description = "Async rust client for divviup.org"

[features]
default = []
admin = []

[dependencies]
base64 = "0.22.0"
email_address = "0.2.4"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"
trillium-client = { version = "0.5.6", features = ["json"] }
trillium-http = "0.3.14"
url = { version = "2.5.0", features = ["serde"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "serde"] }
time = { version = "0.3.34", features = ["serde", "serde-well-known"] }
log = "0.4.21"
pad-adapter = "0.1.1"
janus_messages = "0.6.21"

[dev-dependencies]
divviup-api.workspace = true
fastrand = "2.0.2"
futures-lite = "2.3.0"
test-support.workspace = true
trillium = "0.2.17"
trillium-macros = "0.0.5"
trillium-testing = { version = "0.5.4", features = ["tokio"] }
trillium-rustls = "0.6.0"
trillium-tokio = "0.3.4"
divviup-client =  { path = ".", features = ["admin"] }
