[package]
name = "divviup-client"
version = "0.0.1"
edition = "2021"
license = "MPL-2.0"
homepage = "https://divviup.org"
repository = "https://github.com/divviup/divviup-api"
publish = false

[features]
default = ["admin"]
admin = []

[dependencies]
base64 = "0.21.2"
email_address = "0.2.4"
serde = { version = "1.0.179", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.44"
trillium-client = { version = "0.4.5", features = ["json"] }
trillium-http = "0.3.2"
url = { version = "2.4.0", features = ["serde"] }
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "serde"] }
time = { version = "0.3.25", features = ["serde", "serde-well-known"] }
log = "0.4.20"
pad-adapter = "0.1.1"
janus_messages = "0.5.16"

[dev-dependencies]
divviup-api = { version = "*", path = ".." }
fastrand = "2.0.0"
futures-lite = "1.13.0"
test-support = { path = "../test-support" }
trillium = "0.2.9"
trillium-macros = "0.0.4"
trillium-testing = { version = "0.5.0", features = ["tokio"] }
trillium-rustls = "0.4.0"
trillium-tokio = "0.3.1"
