[package]
name = "divviup-client"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
version.workspace = true
description = "Async rust client for divviup.org"

[features]
default = []
admin = []

[dependencies]
base64 = "0.21.5"
email_address = "0.2.4"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.56"
trillium-client = { version = "0.5.3", features = ["json"] }
trillium-http = "0.3.11"
url = { version = "2.5.0", features = ["serde"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "serde"] }
time = { version = "0.3.31", features = ["serde", "serde-well-known"] }
log = "0.4.20"
pad-adapter = "0.1.1"
janus_messages = "0.6.8"

[dev-dependencies]
divviup-api.workspace = true
fastrand = "2.0.1"
futures-lite = "2.2.0"
test-support.workspace = true
trillium = "0.2.13"
trillium-macros = "0.0.5"
trillium-testing = { version = "0.5.2", features = ["tokio"] }
trillium-rustls = "0.4.2"
trillium-tokio = "0.3.4"
divviup-client =  { path = ".", features = ["admin"] }
