[package]
name = "divviup-api"
version = "0.0.7"
edition = "2021"
publish = false
default-run = "divviup_api_bin"

[features]
default = []
aggregator-api-mock = []
integration-testing = []

[workspace]
members = [".", "migration"]

[dependencies]
async-lock = "2.7.0"
async-session = "3.0.0"
base64 = "0.21.0"
email_address = "0.2.4"
env_logger = "0.10.0"
fastrand = "1.9.0"
git-version = "0.3.5"
janus_messages = "0.4.9"
log = "0.4.17"
opentelemetry = { version = "0.19.0", features = ["metrics"] }
opentelemetry-prometheus = { version = "0.12.0", features = [
    "prometheus-encoding",
] }
prio = "0.12.1"
querystrong = "0.3.0"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_path_to_error = "0.1.11"
test-harness = "0.1.1"
thiserror = "1.0.40"
time = { version = "0.3.21", features = ["serde", "serde-well-known"] }
tokio = { version = "1.28.1", features = ["full"] }
tracing = "0.1.37"
trillium = "0.2.9"
trillium-api = { version = "0.2.0-rc.3", default-features = false }
trillium-caching-headers = "0.2.1"
trillium-client = { version = "0.4.4", features = ["json"] }
trillium-compression = "0.1.0"
trillium-conn-id = "0.2.1"
trillium-cookies = "0.4.0"
trillium-forwarding = "0.2.1"
trillium-http = { version = "0.3.2", features = ["http-compat", "serde"] }
trillium-logger = "0.4.2"
trillium-macros = "0.0.4"
trillium-prometheus = "0.1.0"
trillium-redirect = "0.1.0"
trillium-router = "0.3.5"
trillium-rustls = "0.4.0"
trillium-sessions = "0.4.2"
trillium-static-compiled = "0.5.0"
trillium-tokio = "0.3.1"
url = "2.3.1"
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "serde"] }
validator = { version = "0.16.0", features = ["derive"] }

[dependencies.oauth2]
version = "4.4.0"
default-features = false
features = ["pkce-plain"]

[dependencies.sea-orm]
version = "0.11.3"
features = [
    "runtime-tokio-rustls",
    "macros",
    "sqlx-postgres",
    "with-uuid",
    "with-time",
]

[dev-dependencies]
trillium-testing = { version = "0.5.0", features = ["tokio"] }
sea-orm = { version = "0.11.3", features = ["sqlx-sqlite"] }
regex = "1.8.1"

[build-dependencies]
rustc_version = "0.4.0"

[lib]
name = "divviup_api"
path = "src/lib.rs"

[[bin]]
name = "divviup_api_bin"
path = "src/bin.rs"

[profile.release]
lto = "fat"
