[package]
name = "divviup-api"
version = "0.0.1"
edition = "2021"
publish = false

[workspace]
members = [".", "migration"]

[dependencies]
async-lock = "2.7.0"
async-session = "3.0.0"
base64 = "0.21.0"
env_logger = "0.10.0"
fastrand = "1.9.0"
log = "0.4.17"
querystrong = "0.2.0"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
serde_path_to_error = "0.1.10"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls"] }
thiserror = "1.0.40"
time = { version = "0.3.20", features = ["serde", "serde-well-known"] }
trillium = "0.2.6"
trillium-api = { version = "0.2.0-rc.2", default-features = false }
trillium-caching-headers = "0.2.1"
trillium-client = { version = "0.3.0", features = ["json"] }
trillium-compression = "0.1.0"
trillium-conn-id = "0.2.1"
trillium-cookies = "0.3.0"
trillium-http = { version = "0.2.12", features = ["http-compat"] }
trillium-logger = "0.4.2"
trillium-redirect = "0.1.0"
trillium-router = "0.3.4"
trillium-rustls = "0.2.0"
trillium-sessions = "0.3.0"
trillium-tokio = "0.2.1"
url = "2.3.1"
uuid = { version = "1.3.0", features = ["v4", "fast-rng", "serde"] }
validator = { version = "0.16.0", features = ["derive"] }

[dependencies.oauth2]
version = "4.3.0"
default-features = false
features = ["pkce-plain"]

[dependencies.sea-orm]
version = "0.11.1"
features = [
  "runtime-tokio-rustls",
  "macros",
  "sqlx-postgres",
  "sea-orm-internal",
  "with-uuid",
  "with-time"
]

[lib]
name = "divviup_api"
path = "src/lib.rs"

[[bin]]
name = "divviup_api_bin"
path = "src/bin.rs"


