[package]
name = "divviup-api"
version = "0.0.3"
edition = "2021"
publish = false
default-run = "divviup_api_bin"

[features]
default = []
aggregator-api-mock = []

[workspace]
members = [".", "migration"]

[dependencies]
async-lock = "2.7.0"
async-session = "3.0.0"
base64 = "0.21.0"
env_logger = "0.10.0"
fastrand = "1.9.0"
git-version = "0.3.5"
log = "0.4.17"
opentelemetry = { version = "0.19.0", features = ["metrics"] }
opentelemetry-prometheus = { version = "0.12.0", features = ["prometheus-encoding"] }
querystrong = "0.3.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_path_to_error = "0.1.11"
test-harness = "0.1.1"
thiserror = "1.0.40"
time = { version = "0.3.20", features = ["serde", "serde-well-known"] }
tokio = { version = "1.27.0", features = ["full"] }
trillium = "0.2.8"
trillium-api = { version = "0.2.0-rc.2", default-features = false }
trillium-caching-headers = "0.2.1"
trillium-client = { version = "0.3.1", features = ["json"] }
trillium-compression = "0.1.0"
trillium-conn-id = "0.2.1"
trillium-cookies = "0.4.0"
trillium-forwarding = "0.2.1"
trillium-http = { version = "0.2.14", features = ["http-compat"] }
trillium-logger = "0.4.2"
trillium-macros = "0.0.3"
trillium-prometheus = "0.1.0"
trillium-redirect = "0.1.0"
trillium-router = "0.3.5"
trillium-rustls = "0.2.0"
trillium-sessions = "0.4.1"
trillium-static-compiled = "0.5.0"
trillium-tokio = "0.2.1"
url = "2.3.1"
uuid = { version = "1.3.1", features = ["v4", "fast-rng", "serde"] }
validator = { version = "0.16.0", features = ["derive"] }

[dependencies.oauth2]
version = "4.3.0"
default-features = false
features = ["pkce-plain"]

[dependencies.sea-orm]
version = "0.11.2"
features = [
    "runtime-tokio-rustls",
    "macros",
    "sqlx-postgres",
    "with-uuid",
    "with-time",
]

[dev-dependencies]
trillium-testing = { version = "0.4.2", features = ["tokio"] }
sea-orm = { version = "0.11.2", features = ["sqlx-sqlite"] }
regex = "1.7.3"

[build-dependencies]
rustc_version = "0.4.0"

[lib]
name = "divviup_api"
path = "src/lib.rs"

[[bin]]
name = "divviup_api_bin"
path = "src/bin.rs"

[profile.release]
lto = "fat"

