[package]
name = "divviup-api"
version = "0.0.30"
edition = "2021"
license = "MPL-2.0"
homepage = "https://divviup.org"
repository = "https://github.com/divviup/divviup-api"
publish = false
default-run = "divviup_api_bin"

[features]
default = []
api-mocks = ["dep:trillium-testing"]
integration-testing = []

[workspace]
members = [".", "migration", "client", "test-support", "cli"]

[dependencies]
aes-gcm = "0.10.3"
async-lock = "2.8.0"
async-session = "3.0.0"
base64 = "0.21.4"
email_address = "0.2.4"
env_logger = "0.10.0"
fastrand = "2.0.1"
futures-lite = "1.13.0"
git-version = "0.3.5"
janus_messages = "0.5.24"
log = "0.4.20"
opentelemetry = { version = "0.20.0", features = ["metrics"] }
opentelemetry-prometheus = { version = "0.13.0", features = [
    "prometheus-encoding",
] }
prio = "0.15.3"
prometheus = "0.13.3"
querystrong = "0.3.0"
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
serde_path_to_error = "0.1.14"
sha2 = "0.10.8"
subtle = "2.5.0"
thiserror = "1.0.49"
time = { version = "0.3.30", features = ["serde", "serde-well-known"] }
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.39"
trillium = "0.2.10"
trillium-api = { version = "0.2.0-rc.4", default-features = false }
trillium-caching-headers = "0.2.1"
trillium-client = { version = "0.4.5", features = ["json"] }
trillium-compression = "0.1.0"
trillium-conn-id = "0.2.1"
trillium-cookies = "0.4.0"
trillium-forwarding = "0.2.1"
trillium-http = { version = "0.3.4", features = ["http-compat", "serde"] }
trillium-logger = "0.4.3"
trillium-macros = "0.0.4"
trillium-prometheus = "0.1.0"
trillium-redirect = "0.1.0"
trillium-router = "0.3.5"
trillium-rustls = "0.4.0"
trillium-sessions = "0.4.2"
trillium-static-compiled = "0.5.0"
trillium-testing = { version = "0.5.0", optional = true }
trillium-tokio = "0.3.2"
typenum = "1.17.0"
url = "2.4.1"
uuid = { version = "1.5.0", features = ["v4", "fast-rng", "serde"] }
validator = { version = "0.16.1", features = ["derive"] }

[dependencies.oauth2]
version = "4.4.2"
default-features = false
features = ["pkce-plain"]

[dependencies.sea-orm]
version = "0.12.3"
features = [
    "runtime-tokio-rustls",
    "macros",
    "sqlx-postgres",
    "with-uuid",
    "with-time",
]

[dev-dependencies]
regex = "1.10.2"
test-support = { path = "./test-support" }

[build-dependencies]
rustc_version = "0.4.0"

[lib]
name = "divviup_api"
path = "src/lib.rs"

[[bin]]
name = "divviup_api_bin"
path = "src/bin.rs"

[profile.release]
lto = "fat"
