# Overrides for the local development docker compose setup. Meant only to be used by
# compose.dev.yaml

x-build: &build
  build:
    context: .
    args:
      RUST_PROFILE: dev
      # We don't need both of these features in all three services, but it allows reusing one
      # container image for both this and the divviup_api service.
      RUST_FEATURES: integration-testing,admin

services:
  divviup_api:
    image: !reset null
    <<: *build
    develop:
      watch:
        - path: src/
          action: rebuild

  divviup_api_migrate:
    image: !reset null
    <<: *build
    develop:
      watch:
        - path: migration
          action: rebuild
          ignore:
            - README.md

  pair_aggregator:
    image: !reset null
    <<: *build
    develop:
      watch:
        - path: cli/
          action: rebuild
        - path: client/
          action: rebuild

  # In the development context, we serve static assets using Vite and a bind mount, so that changes
  # to the local assets will immediately be reflected.
  static_assets:
    image: !reset null
    healthcheck: !reset null
    build:
      context: .
      # `develop` cannot be used with an `image` directive, so we need to use a minimal dockerfile
      # containing the image we need.
      dockerfile: Dockerfile.vite
    working_dir: /srv/app
    volumes:
     - type: bind
       source: ./app
       target: /srv/app
    entrypoint:
      - /bin/sh
      - -c
      - npm i && npx vite --host=0.0.0.0
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
