[graph]
targets = [{ triple = "x86_64-unknown-linux-gnu" }, { triple = "x86_64-unknown-linux-musl" }]
all-features = true

[advisories]
version = 2
ignore = [
    "RUSTSEC-2025-0056", # Used by console-subscriber
    "RUSTSEC-2024-0437", # protobuf 2.28.0 via opentelemetry-prometheus → prometheus
    "RUSTSEC-2025-0134", # rustls-pemfile 2.2.0 via reqwest
    "RUSTSEC-2026-0097", # rand 0.8.5 via prometheus
]

[bans]
multiple-versions = "allow"
deny = [{ name = "tracing", deny-multiple-versions = true }, { name = "opentelemetry", deny-multiple-versions = true }]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
allow-org = { github = ["divviup"] }

[licenses]
version = 2
allow = ["MPL-2.0", "MIT", "Apache-2.0", "BSL-1.0", "BSD-2-Clause", "BSD-3-Clause", "Zlib", "Unicode-DFS-2016", "Unicode-3.0", "ISC", "CDLA-Permissive-2.0", "Unlicense", "CC0-1.0"]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
