[package]
name = "divviup-cli"
version = "0.0.1"
edition = "2021"
license = "MPL-2.0"
homepage = "https://divviup.org"
repository = "https://github.com/divviup/divviup-api"
publish = false

[features]
default = ["hpke"]
hpke = ["dep:hpke-dispatch", "dep:rand"]
admin = ["divviup-client/admin"]

[[bin]]
name = "divviup"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.0", features = ["derive", "env"] }
thiserror = "1.0.48"
divviup-client = { path = "../client" }
trillium-rustls = "0.4.0"
trillium-tokio = "0.3.1"
serde = "1.0.188"
email_address = "0.2.4"
humantime = "2.1.0"
base64 = "0.21.3"
time = { version = "0.3.28", features = [
    "serde",
    "serde-well-known",
    "local-offset",
] }
serde_json = "1.0.105"
serde_yaml = "0.9.25"
env_logger = "0.10.0"
colored = "2.0.4"
const_format = "0.2.31"
hpke-dispatch = { version = "0.5.1", features = ["serde"], optional = true }
rand = { version = "0.8.5", optional = true }

