[package]
name = "divviup-cli"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
version.workspace = true
description = "Command line utility for divviup.org"

[features]
default = ["common", "aws-lc-rs"]
common = ["hpke", "trillium-rustls/client", "trillium-rustls/tls12"]
# Building aws-lc-rs on Windows is challenging at best because of aws-lc's toolchain, so we allow
# using ring instead
aws-lc-rs = ["trillium-rustls/aws-lc-rs"]
ring = ["trillium-rustls/ring"]
hpke = ["dep:hpke-dispatch", "dep:rand"]
admin = ["divviup-client/admin"]

[[bin]]
name = "divviup"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4.5.16", features = ["derive", "env"] }
thiserror = "1.0.63"
divviup-client = { workspace = true }
trillium-rustls = { version = "0.8.1", default-features = false }
trillium-tokio = "0.4.0"
serde = "1.0.209"
email_address = "0.2.9"
humantime = "2.1.0"
base64 = "0.22.1"
time = { version = "0.3.36", features = [
    "serde",
    "serde-well-known",
    "local-offset",
] }
serde_json = "1.0.127"
serde_yaml = "0.9.34"
env_logger = "0.11.5"
colored = "2.1.0"
const_format = "0.2.32"
hpke-dispatch = { version = "0.5.1", features = ["serde"], optional = true }
rand = { version = "0.8.5", optional = true }
janus_client = "0.7.21"
janus_collector = "0.7.21"
url = "2.5.2"
janus_messages = "0.7.33"
prio = "0.16.7"
tokio = { version = "1.40.0" }
