[package]
name = "divviup-cli"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "divviup"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3.19", features = ["derive", "env"] }
thiserror = "1.0.44"
divviup-client = { path = "../client" }
trillium-rustls = "0.4.0"
trillium-tokio = "0.3.1"
serde = "1.0.179"
email_address = "0.2.4"
humantime = "2.1.0"
base64 = "0.21.2"
time = { version = "0.3.23", features = [
    "serde",
    "serde-well-known",
    "local-offset",
] }
serde_json = "1.0.103"
serde_yaml = "0.9.25"
env_logger = "0.10.0"
colored = "2.0.4"
const_format = "0.2.31"
