[package]
name = "divviup-cli"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
version.workspace = true
description = "Command line utility for divviup.org"

[features]
default = ["hpke"]
hpke = ["dep:hpke-dispatch", "dep:rand"]
admin = ["divviup-client/admin"]

[[bin]]
name = "divviup"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.11", features = ["derive", "env"] }
thiserror = "1.0.50"
divviup-client = { workspace = true }
trillium-rustls = "0.4.0"
trillium-tokio = "0.3.2"
serde = "1.0.190"
email_address = "0.2.4"
humantime = "2.1.0"
base64 = "0.21.5"
time = { version = "0.3.30", features = [
    "serde",
    "serde-well-known",
    "local-offset",
] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
env_logger = "0.10.0"
colored = "2.0.4"
const_format = "0.2.32"
hpke-dispatch = { version = "0.5.1", features = ["serde"], optional = true }
rand = { version = "0.8.5", optional = true }

