[package]
name = "divviup-cli"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
version.workspace = true
description = "Command line utility for divviup.org"

[features]
default = ["hpke"]
hpke = ["dep:hpke-dispatch", "dep:rand"]
admin = ["divviup-client/admin"]

[[bin]]
name = "divviup"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env"] }
thiserror = "1.0.59"
divviup-client = { workspace = true }
trillium-rustls = "0.8.0"
trillium-tokio = "0.4.0"
serde = "1.0.200"
email_address = "0.2.4"
humantime = "2.1.0"
base64 = "0.22.1"
time = { version = "0.3.36", features = [
    "serde",
    "serde-well-known",
    "local-offset",
] }
serde_json = "1.0.116"
serde_yaml = "0.9.34"
env_logger = "0.11.3"
colored = "2.1.0"
const_format = "0.2.32"
hpke-dispatch = { version = "0.5.1", features = ["serde"], optional = true }
rand = { version = "0.8.5", optional = true }

