[package]
name = "divviup-cli"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
version.workspace = true
description = "Command line utility for divviup.org"

[features]
default = ["hpke"]
hpke = ["dep:hpke-dispatch", "dep:rand"]
admin = ["divviup-client/admin"]

[[bin]]
name = "divviup"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.1", features = ["derive", "env"] }
thiserror = "1.0.57"
divviup-client = { workspace = true }
trillium-rustls = "0.4.2"
trillium-tokio = "0.3.4"
serde = "1.0.196"
email_address = "0.2.4"
humantime = "2.1.0"
base64 = "0.21.7"
time = { version = "0.3.34", features = [
    "serde",
    "serde-well-known",
    "local-offset",
] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
env_logger = "0.11.2"
colored = "2.1.0"
const_format = "0.2.32"
hpke-dispatch = { version = "0.5.1", features = ["serde"], optional = true }
rand = { version = "0.8.5", optional = true }

