---
variant 1: collector credentials first
---

flowchart TD
   NewAccount[New Account] --> ApiToken[Generate an api token\nand store it somewhere safe]
   ApiToken --> UseCli[1. Install the DivviUp cli\n2. `divviup -t API_TOKEN collector-credentials generate`]
   UseCli --> PrivateAggregator{Do you need to pair\na private aggregator?}
   PrivateAggregator-->|Yes| PairPrivateAggregator[create private aggregator: name, url, bearer token]
   PairPrivateAggregator-->NewTask[create your first task]
   PrivateAggregator-->|No| NewTask
