---
variant 2: private aggregator first
---

flowchart TD
   NewAccount[New Account] --> PrivateAggregator{Do you need to pair\na private aggregator?}
   PrivateAggregator-->|Yes| PairPrivateAggregator[create private aggregator: name, url, bearer token]
   PairPrivateAggregator--> ApiToken
   PrivateAggregator-->|No| ApiToken
   ApiToken --> UseCli[1. Install the DivviUp cli\n2. `divviup -t API_TOKEN collector-credentials generate`]
   UseCli --> NewTask[Create your first task]
