name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_docker:
    strategy:
      matrix:
        rust-features: ["default", "integration-testing"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: git
        run: echo "GIT_REVISION=$(git describe --always --dirty=-modified)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          use: true
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: |
            type=gha,scope=main-${{ matrix.rust-features }}
            type=gha,scope=${{ github.ref_name }}-${{ matrix.rust-features }}
          cache-to: type=gha,scope=${{ github.ref_name }}-${{ matrix.rust-features }},mode=max
          build-args: |
            GIT_REVISION=${{ steps.git.outputs.GIT_REVISION }}
            RUST_FEATURES=${{ matrix.rust-features }}
      - name: Compose
        id: compose
        run: docker compose up --wait --wait-timeout 120
        # continue on error so we can inspect containers in the next step
        continue-on-error: true
      - name: Inspect containers
        if: steps.compose.outcome != 'success'
        run: |
          docker compose ps
          for NAME in `docker compose ps --format json | jq -r '.Name'`; do
            docker inspect $NAME
          done
          exit 1
