name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    strategy:
      matrix:
        rust-features: ["default", "integration-testing"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: git
        run: echo "GIT_REVISION=$(git describe --always --dirty=-modified)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          use: true
          buildkitd-flags: --debug
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_REVISION=${{ steps.git.outputs.GIT_REVISION }}
            RUST_FEATURES=${{ matrix.rust-features }}
