name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_docker:
    strategy:
      matrix:
        rust-features: ["default", "integration-testing"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: git
        run: echo "GIT_REVISION=$(git describe --always --dirty=-modified)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          use: true
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          cache-from: |
            type=gha,scope=main-${{ matrix.rust-features }}
            type=gha,scope=${{ github.ref_name }}-${{ matrix.rust-features }}
          cache-to: type=gha,scope=${{ github.ref_name }}-${{ matrix.rust-features }},mode=max
          build-args: |
            GIT_REVISION=${{ steps.git.outputs.GIT_REVISION }}
            RUST_FEATURES=${{ matrix.rust-features }}
      # Test the dev compose, which should use the images built earlier. Technically this is only
      # interesting when feature integration-testing is on, but we may as well exercise both.
      - name: Compose (dev)
        id: compose-dev
        run: docker compose -f compose.dev.yaml up --wait --wait-timeout 120
      - name: Inspect dev containers
        if: ${{ failure() && steps.compose-dev.outcome != 'success' }}
        run: |
          docker compose ps
          for NAME in `docker compose ps --format json | jq -r '.Name'`; do
            docker inspect $NAME
          done

  # Test the non-dev compose, which we use for demo purposes. This pulls images from remote repos,
  # so no need to build anything. Additionally we want coverage across multiple operating systems.
  # Ideally we'd test on macOS, too, but those runners don't have Docker:
  # https://github.com/actions/runner-images/issues/2150
  compose:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          use: true
      - name: Compose
        id: compose
        run: docker compose up --wait --wait-timeout 120
      - name: Inspect containers
        if: ${{ failure() && steps.compose.outcome != 'success' }}
        run: |
          docker compose ps
          for NAME in `docker compose ps --format json | jq -r '.Name'`; do
            docker inspect $NAME
          done
