name: publish-crates

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  crate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v5
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - id: auth
      uses: rust-lang/crates-io-auth-action@v1
    - name: "Publish divviup-client"
      run: cargo publish --package divviup-client
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
    - name: "Publish divviup-cli"
      run: cargo publish --package divviup-cli
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
