name: publish-crates

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.DIVVIUP_GITHUB_AUTOMATION_CRATES_IO_API_TOKEN }}

jobs:
  crate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: "Publish divviup-client"
      run: cargo publish --package divviup-client
    - name: "Publish divviup-cli"
      run: cargo publish --package divviup-cli
